export const ROLES = {
  LANDLORD: 'landlord',
  TENANT: 'tenant'
};

export const PERMISSIONS = {
  AUTH_LOGIN: 'auth.login',
  AUTH_LOGOUT: 'auth.logout',
  AUTH_PROFILE_VIEW: 'auth.profile.view',
  AUTH_PROFILE_UPDATE: 'auth.profile.update',

  TENANT_LIST: 'tenant.list',
  TENANT_CREATE: 'tenant.create',
  TENANT_VIEW: 'tenant.view',
  TENANT_UPDATE: 'tenant.update',
  TENANT_DELETE: 'tenant.delete',
  TENANT_TOGGLE_STATUS: 'tenant.toggle_status',

  ROOM_LIST: 'room.list',
  ROOM_CREATE: 'room.create',
  ROOM_VIEW: 'room.view',
  ROOM_UPDATE: 'room.update',
  ROOM_DELETE: 'room.delete',

  CONTRACT_LIST: 'contract.list',
  CONTRACT_CREATE: 'contract.create',
  CONTRACT_VIEW: 'contract.view',
  CONTRACT_UPDATE: 'contract.update',
  CONTRACT_TERMINATE: 'contract.terminate',

  SERVICE_LIST: 'service.list',
  SERVICE_CREATE: 'service.create',
  SERVICE_VIEW: 'service.view',
  SERVICE_UPDATE: 'service.update',
  SERVICE_DELETE: 'service.delete',

  INVOICE_LIST: 'invoice.list',
  INVOICE_CREATE: 'invoice.create',
  INVOICE_VIEW: 'invoice.view',
  INVOICE_UPDATE: 'invoice.update',
  INVOICE_DELETE: 'invoice.delete',

  // Utility Meter Management
  METER_LIST: 'meter.list',
  METER_CREATE: 'meter.create',
  METER_VIEW: 'meter.view',
  METER_UPDATE: 'meter.update'
};

export const ROLE_PERMISSIONS = {
  [ROLES.LANDLORD]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.AUTH_PROFILE_VIEW,
    PERMISSIONS.AUTH_PROFILE_UPDATE,
    PERMISSIONS.TENANT_LIST,
    PERMISSIONS.TENANT_CREATE,
    PERMISSIONS.TENANT_VIEW,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.TENANT_DELETE,
    PERMISSIONS.TENANT_TOGGLE_STATUS,
    PERMISSIONS.ROOM_LIST,
    PERMISSIONS.ROOM_CREATE,
    PERMISSIONS.ROOM_VIEW,
    PERMISSIONS.ROOM_UPDATE,
    PERMISSIONS.ROOM_DELETE,
    PERMISSIONS.CONTRACT_LIST,
    PERMISSIONS.CONTRACT_CREATE,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.CONTRACT_UPDATE,
    PERMISSIONS.CONTRACT_TERMINATE,
    PERMISSIONS.SERVICE_LIST,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,
    PERMISSIONS.INVOICE_LIST,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_DELETE,
    PERMISSIONS.METER_LIST,
    PERMISSIONS.METER_CREATE,
    PERMISSIONS.METER_VIEW,
    PERMISSIONS.METER_UPDATE
  ],
  [ROLES.TENANT]: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.AUTH_LOGOUT,
    PERMISSIONS.AUTH_PROFILE_VIEW,
    PERMISSIONS.AUTH_PROFILE_UPDATE,
    PERMISSIONS.ROOM_VIEW,
    PERMISSIONS.CONTRACT_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.METER_VIEW
  ]
};

export default {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
